const url ={
    BASE_URL:"http://localhost:8080/api/v3",
    PATIENT:{
        REGISTER:"/patients",
    },
    DEPARTMENT:{
        LIST: "/departments",
        DETAIL:"/departments"
    },
    SHIFT:{
        LIST:"/shifts"
    },
    BOOKING:{
        CREATE:"/bookings",
        LIST:"/bookings",
        UPDATE:"/bookings/updateStatus/",
    },
    RESULT:{
        LIST:"/results",
        CREATE:"/results",
        DETAIL:"/results/findById"
    },
    DOCTOR:{
        LIST:"/doctors",
        LOGIN:"/doctors/login",
        PROFILE:"/doctors/profile"
    },
    DEVICE:{
        LIST:"/devices"
    },
    TEST:{
        CREATE:"/tests",
        LIST:"/tests",
        UPDATE:"/tests"
    },
    RESULTMEDICINE:{
        CREATE:"/result_medicine",
        DETAIL:"/result_medicine/resultId/",
        DELETE:"/result_medicine/"
    },
    MEDICINE:{
        LIST:"/medicine"
    },
    EMAIL:{
        SENT:"/send_email"
    }
}
export default url;